version: '3'
services:
  app:
    build: .
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    command: python /srv/app/app.py
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus:/etc/prometheus
    links:
      - app
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./config/grafana/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
    ports:
      - "3000:3000"
    links:
      - prometheus
